#############################################################################
# Makefile for building: Caesium.app/Contents/MacOS/Caesium
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sun Apr 29 19:29:41 2012
# Project:  ../Caesium/Caesium.pro
# Template: app
# Command: /Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile ../Caesium/Caesium.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ -I../Caesium -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtCore.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtNetwork.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtNetwork -I../../QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtGui.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/4.8.0/gcc/include -I. -I. -I../Caesium -I. -F/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/lib -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Caesium/updater.cpp \
		../Caesium/startupupdater.cpp \
		../Caesium/qdroptreewidget.cpp \
		../Caesium/preferences.cpp \
		../Caesium/main.cpp \
		../Caesium/loadpreview.cpp \
		../Caesium/global.cpp \
		../Caesium/exit.cpp \
		../Caesium/compressionthread.cpp \
		../Caesium/caesium.cpp \
		../Caesium/about.cpp moc_updater.cpp \
		moc_startupupdater.cpp \
		moc_qdroptreewidget.cpp \
		moc_preferences.cpp \
		moc_loadpreview.cpp \
		moc_exit.cpp \
		moc_compressionthread.cpp \
		moc_caesium.cpp \
		moc_about.cpp \
		qrc_icons.cpp
OBJECTS       = updater.o \
		startupupdater.o \
		qdroptreewidget.o \
		preferences.o \
		main.o \
		loadpreview.o \
		global.o \
		exit.o \
		compressionthread.o \
		caesium.o \
		about.o \
		moc_updater.o \
		moc_startupupdater.o \
		moc_qdroptreewidget.o \
		moc_preferences.o \
		moc_loadpreview.o \
		moc_exit.o \
		moc_compressionthread.o \
		moc_caesium.o \
		moc_about.o \
		qrc_icons.o
DIST          = ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		../Caesium/Caesium.pro
QMAKE_TARGET  = Caesium
DESTDIR       = 
TARGET        = Caesium.app/Contents/MacOS/Caesium

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Caesium.app/Contents/PkgInfo Caesium.app/Contents/Resources/empty.lproj Caesium.app/Contents/Info.plist Caesium.app/Contents/Resources/caesium.rc $(TARGET)

$(TARGET): ui_updater.h ui_preferences.h ui_form.h ui_exit.h ui_caesium.h ui_about.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Caesium.app/Contents/MacOS/ || $(MKDIR) Caesium.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Caesium/Caesium.pro  ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile ../Caesium/Caesium.pro
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile ../Caesium/Caesium.pro

Caesium.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Caesium.app/Contents || $(MKDIR) Caesium.app/Contents 
	@$(DEL_FILE) Caesium.app/Contents/PkgInfo
	@echo "APPL????" >Caesium.app/Contents/PkgInfo
Caesium.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Caesium.app/Contents/Resources || $(MKDIR) Caesium.app/Contents/Resources 
	@touch Caesium.app/Contents/Resources/empty.lproj
	
Caesium.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Caesium.app/Contents || $(MKDIR) Caesium.app/Contents 
	@$(DEL_FILE) Caesium.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,caesium.rc,g" -e "s,@EXECUTABLE@,Caesium,g" -e "s,@TYPEINFO@,????,g" ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++/Info.plist.app >Caesium.app/Contents/Info.plist
Caesium.app/Contents/Resources/caesium.rc: ../Caesium/caesium.rc
	@$(CHK_DIR_EXISTS) Caesium.app/Contents/Resources/ || $(MKDIR) Caesium.app/Contents/Resources/ 
	@$(DEL_FILE) Caesium.app/Contents/Resources/caesium.rc
	@$(COPY_FILE) ../Caesium/caesium.rc Caesium.app/Contents/Resources/caesium.rc
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Caesium1.0.0 || $(MKDIR) .tmp/Caesium1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Caesium1.0.0/ && $(COPY_FILE) --parents ../Caesium/updater.h ../Caesium/startupupdater.h ../Caesium/qdroptreewidget.h ../Caesium/preferences.h ../Caesium/loadpreview.h ../Caesium/global.h ../Caesium/exit.h ../Caesium/compressionthread.h ../Caesium/caesium.h ../Caesium/about.h .tmp/Caesium1.0.0/ && $(COPY_FILE) --parents ../Caesium/icons.qrc .tmp/Caesium1.0.0/ && $(COPY_FILE) --parents ../Caesium/updater.cpp ../Caesium/startupupdater.cpp ../Caesium/qdroptreewidget.cpp ../Caesium/preferences.cpp ../Caesium/main.cpp ../Caesium/loadpreview.cpp ../Caesium/global.cpp ../Caesium/exit.cpp ../Caesium/compressionthread.cpp ../Caesium/caesium.cpp ../Caesium/about.cpp .tmp/Caesium1.0.0/ && $(COPY_FILE) --parents ../Caesium/updater.ui ../Caesium/preferences.ui ../Caesium/form.ui ../Caesium/exit.ui ../Caesium/caesium.ui ../Caesium/about.ui .tmp/Caesium1.0.0/ && $(COPY_FILE) --parents caesium_en.ts caesium_it.ts caesium_ja.ts caesium_fr.ts caesium_pt.ts caesium_de.ts caesium_tw.ts caesium_sv.ts caesium_cn.ts .tmp/Caesium1.0.0/ && (cd `dirname .tmp/Caesium1.0.0` && $(TAR) Caesium1.0.0.tar Caesium1.0.0 && $(COMPRESS) Caesium1.0.0.tar) && $(MOVE) `dirname .tmp/Caesium1.0.0`/Caesium1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Caesium1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Caesium.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_updater.cpp moc_startupupdater.cpp moc_qdroptreewidget.cpp moc_preferences.cpp moc_loadpreview.cpp moc_exit.cpp moc_compressionthread.cpp moc_caesium.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_updater.cpp moc_startupupdater.cpp moc_qdroptreewidget.cpp moc_preferences.cpp moc_loadpreview.cpp moc_exit.cpp moc_compressionthread.cpp moc_caesium.cpp moc_about.cpp
moc_updater.cpp: ../Caesium/updater.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/updater.h -o moc_updater.cpp

moc_startupupdater.cpp: ../Caesium/startupupdater.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/startupupdater.h -o moc_startupupdater.cpp

moc_qdroptreewidget.cpp: ../Caesium/qdroptreewidget.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/qdroptreewidget.h -o moc_qdroptreewidget.cpp

moc_preferences.cpp: ../Caesium/preferences.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/preferences.h -o moc_preferences.cpp

moc_loadpreview.cpp: ../Caesium/loadpreview.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/loadpreview.h -o moc_loadpreview.cpp

moc_exit.cpp: ../Caesium/exit.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/exit.h -o moc_exit.cpp

moc_compressionthread.cpp: ../Caesium/compressionthread.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/compressionthread.h -o moc_compressionthread.cpp

moc_caesium.cpp: ../Caesium/compressionthread.h \
		../Caesium/preferences.h \
		../Caesium/about.h \
		../Caesium/updater.h \
		../Caesium/exit.h \
		../Caesium/caesium.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/caesium.h -o moc_caesium.cpp

moc_about.cpp: ../Caesium/about.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../Caesium/about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: ../Caesium/icons.qrc \
		../Caesium/icons/help.png \
		../Caesium/icons/savelist.png \
		../Caesium/icons/exit.png \
		../Caesium/icons/loading.gif \
		../Caesium/icons/error.png \
		../Caesium/icons/qt.png \
		../Caesium/icons/warning.png \
		../Caesium/icons/updates.png \
		../Caesium/icons/savelistas.png \
		../Caesium/icons/save_profile.png \
		../Caesium/icons/preview.png \
		../Caesium/icons/added.png \
		../Caesium/icons/info.png \
		../Caesium/icons/zoom_in.png \
		../Caesium/icons/Italiano.png \
		../Caesium/icons/locale_settings.png \
		../Caesium/icons/caesium_icon.png \
		../Caesium/icons/remove.png \
		../Caesium/icons/general_settings.png \
		../Caesium/icons/caesium_logo.png \
		../Caesium/icons/splash.png \
		../Caesium/icons/done.png \
		../Caesium/icons/compress.png \
		../Caesium/icons/input_dir.png \
		../Caesium/icons/compression_settings.png \
		../Caesium/icons/remove_hdd.png \
		../Caesium/icons/busy.png \
		../Caesium/icons/open_folder.png \
		../Caesium/icons/undo.png \
		../Caesium/icons/search.png \
		../Caesium/icons/skipped.png \
		../Caesium/icons/web.png \
		../Caesium/icons/Deutsch.png \
		../Caesium/icons/English.png \
		../Caesium/icons/Svenska.png \
		../Caesium/icons/load_profile.png \
		../Caesium/icons/plus.png \
		../Caesium/icons/settings.png \
		../Caesium/icons/export.png \
		../Caesium/icons/openlist.png \
		../Caesium/icons/delete.png \
		../Caesium/icons/processing.png \
		../Caesium/icons/fit_window.png \
		../Caesium/icons/real_size.png \
		../Caesium/icons/clear.png \
		../Caesium/icons/add.png \
		../Caesium/icons/output_dir.png \
		../Caesium/icons/zoom_out.png \
		../Caesium/icons/donate.png
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/rcc -name icons ../Caesium/icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_updater.h ui_preferences.h ui_form.h ui_exit.h ui_caesium.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_updater.h ui_preferences.h ui_form.h ui_exit.h ui_caesium.h ui_about.h
ui_updater.h: ../Caesium/updater.ui
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic ../Caesium/updater.ui -o ui_updater.h

ui_preferences.h: ../Caesium/preferences.ui
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic ../Caesium/preferences.ui -o ui_preferences.h

ui_form.h: ../Caesium/form.ui
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic ../Caesium/form.ui -o ui_form.h

ui_exit.h: ../Caesium/exit.ui
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic ../Caesium/exit.ui -o ui_exit.h

ui_caesium.h: ../Caesium/caesium.ui \
		../Caesium/qdroptreewidget.h
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic ../Caesium/caesium.ui -o ui_caesium.h

ui_about.h: ../Caesium/about.ui
	/Users/daisuke/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic ../Caesium/about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

updater.o: ../Caesium/updater.cpp ../Caesium/updater.h \
		ui_updater.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o updater.o ../Caesium/updater.cpp

startupupdater.o: ../Caesium/startupupdater.cpp ../Caesium/startupupdater.h \
		../Caesium/caesium.h \
		../Caesium/compressionthread.h \
		../Caesium/preferences.h \
		../Caesium/about.h \
		../Caesium/updater.h \
		../Caesium/exit.h \
		ui_caesium.h \
		../Caesium/qdroptreewidget.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startupupdater.o ../Caesium/startupupdater.cpp

qdroptreewidget.o: ../Caesium/qdroptreewidget.cpp ../Caesium/qdroptreewidget.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdroptreewidget.o ../Caesium/qdroptreewidget.cpp

preferences.o: ../Caesium/preferences.cpp ../Caesium/preferences.h \
		ui_preferences.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o ../Caesium/preferences.cpp

main.o: ../Caesium/main.cpp ../Caesium/caesium.h \
		../Caesium/compressionthread.h \
		../Caesium/preferences.h \
		../Caesium/about.h \
		../Caesium/updater.h \
		../Caesium/exit.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Caesium/main.cpp

loadpreview.o: ../Caesium/loadpreview.cpp ../Caesium/loadpreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadpreview.o ../Caesium/loadpreview.cpp

global.o: ../Caesium/global.cpp ../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o global.o ../Caesium/global.cpp

exit.o: ../Caesium/exit.cpp ../Caesium/exit.h \
		ui_exit.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exit.o ../Caesium/exit.cpp

compressionthread.o: ../Caesium/compressionthread.cpp ../Caesium/compressionthread.h \
		../Caesium/caesium.h \
		../Caesium/preferences.h \
		../Caesium/about.h \
		../Caesium/updater.h \
		../Caesium/exit.h \
		ui_caesium.h \
		../Caesium/qdroptreewidget.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compressionthread.o ../Caesium/compressionthread.cpp

caesium.o: ../Caesium/caesium.cpp ../Caesium/caesium.h \
		../Caesium/compressionthread.h \
		../Caesium/preferences.h \
		../Caesium/about.h \
		../Caesium/updater.h \
		../Caesium/exit.h \
		ui_caesium.h \
		../Caesium/qdroptreewidget.h \
		../Caesium/startupupdater.h \
		../Caesium/global.h \
		../Caesium/loadpreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caesium.o ../Caesium/caesium.cpp

about.o: ../Caesium/about.cpp ../Caesium/about.h \
		ui_about.h \
		../Caesium/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o ../Caesium/about.cpp

moc_updater.o: moc_updater.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_updater.o moc_updater.cpp

moc_startupupdater.o: moc_startupupdater.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startupupdater.o moc_startupupdater.cpp

moc_qdroptreewidget.o: moc_qdroptreewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdroptreewidget.o moc_qdroptreewidget.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_loadpreview.o: moc_loadpreview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadpreview.o moc_loadpreview.cpp

moc_exit.o: moc_exit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exit.o moc_exit.cpp

moc_compressionthread.o: moc_compressionthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_compressionthread.o moc_compressionthread.cpp

moc_caesium.o: moc_caesium.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_caesium.o moc_caesium.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

